<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title><? $t->block('title') ?>G Battle<? $t->end() ?></title>
        <link href="/css/foundation.min.css" rel="stylesheet">
        <link href="/css/common.css" rel="stylesheet">
        <? $t->block('css') ?><? $t->end() ?>
    </head>
    <body>
        <nav class="top-bar" data-topbar role="navigation">
            <ul class="title-area">
                <li class="name">
                    <h1><a href="/">Gundam Battle</a></h1>
                </li>
            </ul>
            <section class="top-bar-section">
                <ul class="right">
                    <li class="has-dropdown">
                        <? if (M('User')->current()): ?>
                            <a href="/home">你好，<?= name_or_email(M('User')->current()) ?></a>
                        <? endif ?>
                        <ul class="dropdown">
                            <li><a href="/home">个人中心</a></li>
                            <li><a href="/notice">通知</a></li>
                        </ul>
                    </li>
                    <li>
                        <? if (M('User')->current()): ?>
                        <a href="/signout">退出</a>
                        <? else: ?>
                        <a href="/">未登录</a>
                        <? endif ?>
                    </li>
                </ul>
            </section>
        </nav>
        <div class="row"><? $t->block('content') ?><? $t->end() ?></div>
        <div class="row">
            <div class="medium-12 text-center">Copyright &copy 2014 G Battle Team</div>
        </div>
        <script src="/js/jquery.min.js"></script>
        <script src="/js/foundation.min.js"></script>
        <script src="/js/common.js"></script>
        <? $t->block('js') ?><? $t->end() ?>
    </body>
</html>