<? $t->layout = 'layout/main' ?>

<? $t->block('content') ?>
<div class="small-12 columns" style="margin-top: 30px;">
    <div class="row">
        <div class="small-3 columns text-center">
            <div class="row" >
                <div class="small-12 columns">
                    <img src="<?= $user['avatar'] ?>" style="height: 180px"/>
                </div>
            </div>
            <div class="row" >
                <a href="#" data-reveal-id="upload-avatar">上传头像</a>
            </div>
        </div>
        <div class="small-4 columns left">
            <form action="/user/edit" method="post" >
                <div class="row">
                    <div class="small-12 columns">
                        <label>名称
                            <input type="text" value="<?= $user['name'] ?>"/>
                        </label>
                    </div>
                </div>
                <div class="row">
                    <div class="small-12 columns">
                        <label>邮箱
                            <input type="text" value="<?= $user['email'] ?>"/>
                        </label>
                    </div>
                </div>
                <div class="row">
                    <div class="small-12 columns">
                        <button class="tiny">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row" style="margin-top: 20px">
        <div class="small-12 columns">我的相册<a class="tiny right" data-reveal-id="upload-image">上传新图</a></div>
        <hr/>
        <div class="small-12 columns">
            <? $len = count($works) ?>
            <? for($i = 0; $i < $len; $i = $i+4): ?>
            <div class="row">
                <? for($j = $i; $j < $i + 4 && $j < $len; $j++): ?>
                <div class="small-3 columns" style="margin-bottom: 10px;">
                <? $work = $works[$j] ?>
                    <a href="/work/<?=$work['id']?>"><img src="<?=$work['cover']['url']?>"/></a>
                <?=$work['series']['name']?> - <?=$work['item']['name']?>
                </div>
                <? endfor ?>
            </div>
            <? endfor ?>
        </div>
        <div></div>
    <hr/>
    </div>
</div>
<div id="upload-avatar" class="reveal-modal small" data-reveal>
    <form action="/upload-avatar" method="post" enctype="multipart/form-data">
        <input type="hidden" name="rt" value="/home"/>
        <h3>上传头像</h3>
        <p><input name="image" type="file"/></p>
        <button class="button tiny">提交</button>
    </form>
    <a class="close-reveal-modal">&#215;</a>
</div>
<div id="upload-image" class="reveal-modal small" data-reveal>
    <form action="/work/upload" method="post" enctype="multipart/form-data">
        <input type="hidden" name="rt" value="/home"/>
        <h3>上传图片</h3>
        <div class="row">
            <div class="small-6 columns">
                <label>
                    <select id="series-droplist">
                        <option>选择系列</option>
                        <? foreach($series as $id => $val): ?>
                        <option value="<?=$id?>"><?=$val['name']?></option>
                        <? endforeach ?>
                    </select>
                </label>
            </div>
            <div class="small-6 columns">
                <label>
                    <? foreach($series as $id => $val): ?>
                    <select id="item-droplist-<?=$id?>" class="item-droplist <?=$id == 1 ? '' : 'none'?>" >
                        <option>选择模型</option>
                        <? foreach($val['items'] as $tid => $item): ?>
                        <option value="<?=$tid?>"><?=$item['name']?></option>
                        <? endforeach ?>
                    </select>
                    <? endforeach ?>
                </label>
            </div>
            <div></div>
        </div>
        <div class="row">
            <div class="small-12 columns">
                <input type="file" name="image"/>
            </div>
            <div class="small-12 columns">
                <button class="button tiny">提交</button>
            </div>
        </div>
    </form>
    <a class="close-reveal-modal">&#215;</a>
</div>
<? $t->end() ?>